spring:
  application:
    name: customer-ms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: truedatasource:
    driver-class-name: org.postgresql.Driver
    url: ${dburl}
    username: ${dbuser}
    password: ${dbpassword}
