spring:
  application:
    name: customer-ms
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#eureka
eureka:
  server:
    client-url:
      defaultZone: http://localhost:6789/eureka

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO

#common endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
