spring:
  application:
    name: customer-ms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  
#eureka
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:6789/eureka

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO

#common endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
