spring:
  application:
    name: configserver-ms
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/JediSohan/MSPROJECT
          default-label: main
          search-paths:
            - appconfigurations/{application}
          username: JediSohan
          password: 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


server:
  port: 1234